name: Communauté — CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "services/communaute/**"
      - ".github/workflows/communaute.yml"
      - ".github/workflows/ci-template.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/communaute/**"
      - ".github/workflows/communaute.yml"
      - ".github/workflows/ci-template.yml"

jobs:
  pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: communaute
      service_path: services/communaute
      k8s_deployment: communaute
      k8s_namespace: maison-epouvante
    secrets: inherit
