name: Vente â€” CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "services/vente/**"
      - ".github/workflows/vente.yml"
      - ".github/workflows/ci-template.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/vente/**"
      - ".github/workflows/vente.yml"
      - ".github/workflows/ci-template.yml"

jobs:
  pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: vente
      service_path: services/vente
      k8s_deployment: vente
      k8s_namespace: maison-epouvante
    secrets: inherit
